server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql:///cloud_user?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  shardingsphere:
    sharding:
     default-database-strategy:
     tables:
#  application:
#    name: userservice
#  cloud:
#    nacos:
#      server-addr: localhost:8848
#      discovery:
#        cluster-name: SH
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug

#  pattern:
#    dateformat: MM-dd HH:mm:ss:SSS
#eureka:
#  client:
#    service-url:  # eureka的地址信息
#      defaultZone: http://127.0.0.1:10088/eureka
#    registerWithEureka: false
#    fetchRegistry: false
#
#pattern:
#  name: 本地环境local