server:
  port: 10088 # 服务端口

  enable-self-preservation: false
spring:
  application:
    name: eureka-server # eureka的服务名称
  security:
    user:
      name: admin   #用户名
      password: 1   #密码
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:  # eureka的地址信息
      defaultZone: http://127.0.0.1:10088/eureka



